env:
  global:
    - DATABASE_URL_TEST=postgres://tebuqnsm:tqujpRvDZlA85f33IlmJFu0o47eC-rUa@tantor.db.elephantsql.com:5432/tebuqnsm
language: node_js
node_js: 
  - "stable"
before_install:
    - "npm install"
