language: node_js
node_js: 
  - "stable"
  addons:
    code_climate:
        repo_token: f20205d9359a1d70cf0a56b19b484b059e893a8f916ce34646b9ae61a53447c5
script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
before_script:
    - npm install codeclimate-test-reporter istanbul -g
after_script:
    - codeclimate-test-reporter < ./coverage/lcov.info
before_install:
    - "npm install"
after_success:
    - npm run coveralls

